rootProject.name = 'spring-petclinic-NEW'

pluginManagement {
  repositories {
    maven { url 'localhost:8081/repository/maven-public/' }
    allowInsecureProtocol = true
  }
}

dependencyResolutionManagement {
    repositories {
    maven { url 'localhost:8081/repository/maven-public/' }
    allowInsecureProtocol = true
  }
}